apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodRestartingTooMuch
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting too frequently"
        description: "Pod {{ $labels.pod }} restarted more than 3 times in 5 minutes."

